name: 'bagbyte/use-private-action'
description: 'This action allows the use of custom actions in private GitHub repositories.'
author: 'bagbyte'
branding: 
  icon: 'external-link'
  color: 'gray-dark'
inputs:
  private-action:
    description: 'Private action to execute, format: {org}/{repo}[/path]@ref'
    required: true
  private-action-token:
    description: 'Token to access the private repository'
    required: true
  private-action-with:
    description: 'Pass string of (Yaml or Json dictionary of inputs) to be passed into the action being run'
    required: false
runs:
  using: 'node12'
  main: 'dist/main.js'
